image: golang:1.12

definitions: 
  steps:
    - step: &build
        name: Build
        script:
          - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_FULL_NAME}"
          - mkdir -pv "${PACKAGE_PATH}"
          - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
          - cd "${PACKAGE_PATH}"
          - echo "${PACKAGE_PATH}"
          - echo ${BITBUCKET_REPO_FULL_NAME}"
          - echo ${GOPATH}"
          # Install dep to manage dependency versions
          - go get -u github.com/golang/dep/cmd/dep
          - dep ensure -v
          - cd cmd/vodacom-api
          - go build -v
          - mv vodacom-api ${BITBUCKET_CLONE_DIR}/cmd/vodacom-api/
        artifacts:
          - cmd/vodacom-api/**


pipelines:

  custom:
    build:
      - step: *build  
